### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ma00** [GrappleGQL/wagtail-grapple#203]
On wagtail 2.14, after installing version 0.12 I get this error when I try to run server:
ModuleNotFoundError: No module named 'grapple'

**Comment by zerolab** [comment]
Please can you provide a full stack trace?

**Comment by ma00** [comment]
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/utente/anaconda/envs/base2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grapple'

**Comment by zerolab** [comment]
Nothing there to indicate anything. Are you certain the package was installed. What does `pip show wagtail_grapple` say?

**Comment by ma00** [comment]
pip show wagtail_grapple
Name: wagtail-grapple
Version: 0.12.0
Summary: A Django app that speeds up and simplifies implementing a GraphQL endpoint!
Home-page: https://github.com/GrappleGQL/wagtail-grapple
Author: Nathan Horrigan
Author-email: nathan.horrigan@torchbox.com
License: UNKNOWN
Location: /usr/local/lib/python3.8/site-packages
Requires: Django, graphene-django, graphql-core, wagtail, wagtail-headless-preview
Required-by:

**Comment by zerolab** [comment]
Hmm, it looks like grapple is installed globally (`/usr/local/lib/python3.8/site-packages`) whereas you're getting an error in your virtual environment (`/Users/utente/anaconda/envs/base2/lib/python3.8/site-packages/`). Best to activate your virtual environment and install it there.

I do recommend joining the Wagtail Slack - see https://github.com/wagtail/wagtail/wiki/Slack for more details. There are lots of people who can help.

Will close this issue as it is not a package issue as far as I can see. Should it indeed be a grapple issue, will happily re-open with further information
