### ISSUE TITLE
Error when trying to add queries for user

### ISSUE THREAD

**Issue by Didericis** [GrappleGQL/wagtail-grapple#213]
Hey, thanks for this package, is pretty great so far. I've ran into an issue when trying to register a query field for a django user, though. This is what the models file for the user currently looks like:

```py
# search/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from grapple.helpers import register_query_field
from grapple.models import (
    GraphQLString, GraphQLStreamfield
)


@register_query_field('user')
class User(AbstractUser):
    country = models.CharField(verbose_name='country', max_length=255)

    graphql_fields = [
        GraphQLString("email"),
        GraphQLStreamfield("country"),
    ]
```

When I hit the api, I get the following error:

```

  | Internal Server Error: /api/graphql/
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
  |     response = get_response(request)
  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  |     return view_func(*args, **kwargs)
  |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 63, in view
  |     self = cls(**initkwargs)
  |   File "/usr/local/lib/python3.8/site-packages/graphene_django/views.py", line 100, in __init__
  |     schema = graphene_settings.SCHEMA
  |   File "/usr/local/lib/python3.8/site-packages/graphene_django/settings.py", line 126, in __getattr__
  |     val = perform_import(val, attr)
  |   File "/usr/local/lib/python3.8/site-packages/graphene_django/settings.py", line 65, in perform_import
  |     return import_from_string(val, setting_name)
  |   File "/usr/local/lib/python3.8/site-packages/graphene_django/settings.py", line 79, in import_from_string
  |     module = importlib.import_module(module_path)
  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
  |     return _bootstrap._gcd_import(name[level:], package, level)
  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  |   File "/usr/local/lib/python3.8/site-packages/grapple/schema.py", line 86, in <module>
  |     schema = create_schema()
  |   File "/usr/local/lib/python3.8/site-packages/grapple/schema.py", line 77, in create_schema
  |     return graphene.Schema(
  |   File "/usr/local/lib/python3.8/site-packages/graphene/types/schema.py", line 78, in __init__
  |     self.build_typemap()
  |   File "/usr/local/lib/python3.8/site-packages/graphene/types/schema.py", line 167, in build_typemap
  |     self._type_map = TypeMap(
  |   File "/usr/local/lib/python3.8/site-packages/graphene/types/typemap.py", line 80, in __init__
  |     super(TypeMap, self).__init__(types)
  |   File "/usr/local/lib/python3.8/site-packages/graphql/type/typemap.py", line 31, in __init__
  |     self.update(reduce(self.reducer, types, OrderedDict()))  # type: ignore
  |   File "/usr/local/lib/python3.8/site-packages/graphene/types/typemap.py", line 88, in reducer
  |     return self.graphene_reducer(map, type)
  |   File "/usr/local/lib/python3.8/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
  |     return GraphQLTypeMap.reducer(map, internal_type)
  |   File "/usr/local/lib/python3.8/site-packages/graphql/type/typemap.py", line 109, in reducer
  |     field_map = type_.fields
  |   File "/usr/local/lib/python3.8/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
  |     value = obj.__dict__[self.func.__name__] = self.func(obj)
  |   File "/usr/local/lib/python3.8/site-packages/graphql/type/definition.py", line 198, in fields
  |     return define_field_map(self, self._fields)
  |   File "/usr/local/lib/python3.8/site-packages/graphql/type/definition.py", line 212, in define_field_map
  |     field_map = field_map()
  |   File "/usr/local/lib/python3.8/site-packages/graphene/types/typemap.py", line 275, in construct_fields_for_type
  |     map = self.reducer(map, field.type)
  |   File "/usr/local/lib/python3.8/site-packages/graphene/types/field.py", line 119, in type
  |     return get_type(self._type)
  |   File "/usr/local/lib/python3.8/site-packages/graphene/types/utils.py", line 45, in get_type
  |     return _type()
  |   File "/usr/local/lib/python3.8/site-packages/grapple/helpers.py", line 69, in <lambda>
  |     field_type = lambda: registry.models[cls]
  | KeyError: <class 'search.models.User'>
  | [08/Feb/2022 22:38:17] "POST /api/graphql/? HTTP/1.1" 500 18008
```

I poked around in the registry code to try to figure out what's going on, haven't figured out the issue yet. Any pointers/ideas?

**Comment by Didericis** [comment]
@zerolab 🤦  that did it! Thanks, appreciate the fast reply!
